# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1363, 920)
        MainWindow.setStyleSheet("background-color: rgb(65,65,65);\n"
"QPushButton{\n"
"    border-radius:2;\n"
"    background-color: #E1E1E1;\n"
"    border-color:#B7B7B7;\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:2;\n"
"    background-color: #E5F1FB;\n"
"    border-color:#B7B7B7;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-radius:2;\n"
"    background-color: #CCE4F7;\n"
"    border-color:#B7B7B7;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(50, 40, 50, 40)
        self.gridLayout_3.setSpacing(50)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_7.setSpacing(15)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setStyleSheet("background-color: rgb(40, 40,40);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_20.setContentsMargins(50, 30, 50, 30)
        self.gridLayout_20.setSpacing(30)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setContentsMargins(2, 2, 2, 2)
        self.formLayout_9.setVerticalSpacing(15)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(240, 240,240);")
        self.label_14.setObjectName("label_14")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(230, 230,230);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(240, 240,240);")
        self.label_15.setObjectName("label_15")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_13.sizePolicy().hasHeightForWidth())
        self.lineEdit_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(230, 230,230);")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_13)
        self.gridLayout_20.addLayout(self.formLayout_9, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(19)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:rgb(150, 150, 150);")
        self.label_19.setObjectName("label_19")
        self.gridLayout_20.addWidget(self.label_19, 0, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_13.setStyleSheet("color: rgb(140, 160, 220);background-color: rgb(30, 30,30);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_20.addWidget(self.pushButton_13, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_4, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_7, 0, 2, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(40, 40,40);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(50, 30, 50, 30)
        self.gridLayout_2.setSpacing(30)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(2, 2, 2, 2)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(240, 240,240);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(230, 230,230);")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(240, 240,240);")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(240, 240,240);")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(240, 240,240);")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(230, 230,230);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(230, 230,230);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(230, 230,230);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.gridLayout_2.addLayout(self.formLayout, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(150, 150, 150);")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_14.setStyleSheet("color: rgb(140, 160, 220);background-color: rgb(30, 30,30);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_2.addWidget(self.pushButton_14, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_23.setSpacing(15)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        self.frame_11.setStyleSheet("background-color: rgb(40, 40,40);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_24.setContentsMargins(50, 30, 50, 30)
        self.gridLayout_24.setSpacing(30)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.pushButton_29 = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_29.sizePolicy().hasHeightForWidth())
        self.pushButton_29.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_29.setStyleSheet("color: rgb(140, 160, 220);background-color: rgb(30, 30,30);")
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_24.addWidget(self.pushButton_29, 3, 0, 1, 1)
        self.formLayout_14 = QtWidgets.QFormLayout()
        self.formLayout_14.setContentsMargins(2, 2, 2, 2)
        self.formLayout_14.setVerticalSpacing(15)
        self.formLayout_14.setObjectName("formLayout_14")
        self.label_16 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(240, 240,240);")
        self.label_16.setObjectName("label_16")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_14.sizePolicy().hasHeightForWidth())
        self.lineEdit_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(230, 230,230);")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_14)
        self.label_17 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(240, 240,240);")
        self.label_17.setObjectName("label_17")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_15.sizePolicy().hasHeightForWidth())
        self.lineEdit_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(230, 230,230);")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_15)
        self.gridLayout_24.addLayout(self.formLayout_14, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(19)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:rgb(150, 150, 150);")
        self.label_20.setObjectName("label_20")
        self.gridLayout_24.addWidget(self.label_20, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.frame_11, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_23, 0, 1, 1, 1)
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_27.setSpacing(15)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.frame_13 = QtWidgets.QFrame(self.centralwidget)
        self.frame_13.setStyleSheet("background-color: rgb(40, 40,40);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_28.setContentsMargins(50, 30, 50, 30)
        self.gridLayout_28.setSpacing(30)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.pushButton_31 = QtWidgets.QPushButton(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_31.sizePolicy().hasHeightForWidth())
        self.pushButton_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_31.setStyleSheet("color: rgb(140, 160, 220);background-color: rgb(30, 30,30);")
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_28.addWidget(self.pushButton_31, 3, 0, 1, 1)
        self.formLayout_28 = QtWidgets.QFormLayout()
        self.formLayout_28.setContentsMargins(2, 2, 2, 2)
        self.formLayout_28.setVerticalSpacing(15)
        self.formLayout_28.setObjectName("formLayout_28")
        self.label_23 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(240, 240,240);")
        self.label_23.setObjectName("label_23")
        self.formLayout_28.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_18.sizePolicy().hasHeightForWidth())
        self.lineEdit_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(230, 230,230);")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.formLayout_28.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_18)
        self.label_24 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(240, 240,240);")
        self.label_24.setObjectName("label_24")
        self.formLayout_28.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_19.sizePolicy().hasHeightForWidth())
        self.lineEdit_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(230, 230,230);")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.formLayout_28.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_19)
        self.gridLayout_28.addLayout(self.formLayout_28, 1, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(19)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color:rgb(150, 150, 150);")
        self.label_25.setObjectName("label_25")
        self.gridLayout_28.addWidget(self.label_25, 0, 0, 1, 1)
        self.gridLayout_27.addWidget(self.frame_13, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_27, 1, 0, 1, 1)
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_29.setSpacing(15)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.frame_14 = QtWidgets.QFrame(self.centralwidget)
        self.frame_14.setStyleSheet("background-color: rgb(40, 40,40);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_30.setContentsMargins(50, 30, 50, 30)
        self.gridLayout_30.setSpacing(30)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.pushButton_32 = QtWidgets.QPushButton(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_32.sizePolicy().hasHeightForWidth())
        self.pushButton_32.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_32.setStyleSheet("color: rgb(140, 160, 220);background-color: rgb(30, 30,30);")
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_30.addWidget(self.pushButton_32, 3, 0, 1, 1)
        self.formLayout_29 = QtWidgets.QFormLayout()
        self.formLayout_29.setContentsMargins(2, 2, 2, 2)
        self.formLayout_29.setVerticalSpacing(15)
        self.formLayout_29.setObjectName("formLayout_29")
        self.label_26 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(240, 240,240);")
        self.label_26.setObjectName("label_26")
        self.formLayout_29.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_20.sizePolicy().hasHeightForWidth())
        self.lineEdit_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(230, 230,230);")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.formLayout_29.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_20)
        self.label_27 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(240, 240,240);")
        self.label_27.setObjectName("label_27")
        self.formLayout_29.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_21.sizePolicy().hasHeightForWidth())
        self.lineEdit_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(230, 230,230);")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.formLayout_29.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_21)
        self.gridLayout_30.addLayout(self.formLayout_29, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(19)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color:rgb(150, 150, 150);")
        self.label_28.setObjectName("label_28")
        self.gridLayout_30.addWidget(self.label_28, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.frame_14, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_29, 1, 1, 1, 1)
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_31.setSpacing(15)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setStyleSheet("background-color: rgb(40, 40,40);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_32.setContentsMargins(50, 30, 50, 30)
        self.gridLayout_32.setSpacing(30)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_33.sizePolicy().hasHeightForWidth())
        self.pushButton_33.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_33.setStyleSheet("color: rgb(140, 160, 220);background-color: rgb(30, 30,30);")
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout_32.addWidget(self.pushButton_33, 3, 0, 1, 1)
        self.formLayout_30 = QtWidgets.QFormLayout()
        self.formLayout_30.setContentsMargins(2, 2, 2, 2)
        self.formLayout_30.setVerticalSpacing(15)
        self.formLayout_30.setObjectName("formLayout_30")
        self.label_29 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(240, 240,240);")
        self.label_29.setObjectName("label_29")
        self.formLayout_30.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_22.sizePolicy().hasHeightForWidth())
        self.lineEdit_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(230, 230,230);")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.formLayout_30.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_22)
        self.label_30 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(240, 240,240);")
        self.label_30.setObjectName("label_30")
        self.formLayout_30.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_23.sizePolicy().hasHeightForWidth())
        self.lineEdit_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(230, 230,230);")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.formLayout_30.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_23)
        self.gridLayout_32.addLayout(self.formLayout_30, 1, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(19)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color:rgb(150, 150, 150);")
        self.label_31.setObjectName("label_31")
        self.gridLayout_32.addWidget(self.label_31, 0, 0, 1, 1)
        self.gridLayout_31.addWidget(self.frame_15, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_31, 1, 2, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.lineEdit_12.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_14.setText(_translate("MainWindow", "COM:"))
        self.label_15.setText(_translate("MainWindow", "波特率："))
        self.label_19.setText(_translate("MainWindow", "数传端口设置"))
        self.pushButton_13.setText(_translate("MainWindow", "保存设置"))
        self.label_2.setText(_translate("MainWindow", "服务器IP："))
        self.label_3.setText(_translate("MainWindow", "数据库名称："))
        self.label_4.setText(_translate("MainWindow", "用户名："))
        self.label_5.setText(_translate("MainWindow", "密码："))
        self.label.setText(_translate("MainWindow", "远程数据库设置"))
        self.pushButton_14.setText(_translate("MainWindow", "保存设置"))
        self.pushButton_29.setText(_translate("MainWindow", "保存设置"))
        self.label_16.setText(_translate("MainWindow", "URL:"))
        self.label_17.setText(_translate("MainWindow", "图片保存路径："))
        self.label_20.setText(_translate("MainWindow", "图传视频设置"))
        self.pushButton_31.setText(_translate("MainWindow", "保存设置"))
        self.label_23.setText(_translate("MainWindow", "URL:"))
        self.label_24.setText(_translate("MainWindow", "图片保存路径："))
        self.label_25.setText(_translate("MainWindow", "图传视频设置"))
        self.pushButton_32.setText(_translate("MainWindow", "保存设置"))
        self.label_26.setText(_translate("MainWindow", "URL:"))
        self.label_27.setText(_translate("MainWindow", "图片保存路径："))
        self.label_28.setText(_translate("MainWindow", "图传视频设置"))
        self.pushButton_33.setText(_translate("MainWindow", "保存设置"))
        self.label_29.setText(_translate("MainWindow", "URL:"))
        self.label_30.setText(_translate("MainWindow", "图片保存路径："))
        self.label_31.setText(_translate("MainWindow", "图传视频设置"))

