# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1350, 867)
        MainWindow.setStyleSheet("QMessageBox{font-size:20px; }\n"
"QMainWindow{background-color: rgb(65,65,65);color: rgb(250, 250, 250);}\n"
"QWidget{background-color: rgb(65,65,65);color: rgb(250, 250, 250);}\n"
"QGridLayout{background-color: rgb(65,65,65);}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(80, 230, 80, 230)
        self.gridLayout_3.setHorizontalSpacing(80)
        self.gridLayout_3.setVerticalSpacing(100)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(40, 40,40);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(40, 20, 50, 40)
        self.gridLayout_2.setSpacing(30)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(2, 2, 2, 2)
        self.formLayout.setHorizontalSpacing(5)
        self.formLayout.setVerticalSpacing(22)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(240, 240,240);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(220, 220,220);color: rgb(0, 0,0);")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(240, 240,240);")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(240, 240,240);")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(240, 240,240);")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(220, 220,220);color: rgb(0, 0,0);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(220, 220,220);color: rgb(0, 0,0);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(220, 220,220);color: rgb(0, 0,0);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.gridLayout_2.addLayout(self.formLayout, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(150, 150, 150);")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton1 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton1.sizePolicy().hasHeightForWidth())
        self.pushButton1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton1.setFont(font)
        self.pushButton1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton1.setStyleSheet("color: rgb(220, 70, 70);background-color: rgb(30, 30,30);")
        self.pushButton1.setObjectName("pushButton1")
        self.gridLayout_2.addWidget(self.pushButton1, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_7.setSpacing(15)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setStyleSheet("background-color: rgb(40, 40,40);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_20.setContentsMargins(40, 20, 50, 40)
        self.gridLayout_20.setSpacing(30)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setContentsMargins(2, 2, 2, 2)
        self.formLayout_9.setHorizontalSpacing(5)
        self.formLayout_9.setVerticalSpacing(22)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(240, 240,240);")
        self.label_14.setObjectName("label_14")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(240, 240,240);")
        self.label_15.setObjectName("label_15")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.comboBox = QtWidgets.QComboBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(220, 220,220);color: rgb(0, 0,0);")
        self.comboBox.setObjectName("comboBox")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(220, 220,220);color: rgb(0, 0,0);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(100, 100, 200);background-color: rgb(30, 30,30);")
        self.pushButton.setObjectName("pushButton")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(240, 240,240);")
        self.label_18.setObjectName("label_18")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.gridLayout_20.addLayout(self.formLayout_9, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:rgb(150, 150, 150);")
        self.label_19.setObjectName("label_19")
        self.gridLayout_20.addWidget(self.label_19, 0, 0, 1, 1)
        self.pushButton2 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton2.sizePolicy().hasHeightForWidth())
        self.pushButton2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton2.setFont(font)
        self.pushButton2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton2.setStyleSheet("color: rgb(220, 70, 70);background-color: rgb(30, 30,30);")
        self.pushButton2.setObjectName("pushButton2")
        self.gridLayout_20.addWidget(self.pushButton2, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_4, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_7, 0, 2, 1, 1)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_23.setSpacing(15)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        self.frame_11.setStyleSheet("background-color: rgb(40, 40,40);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_24.setContentsMargins(40, 20, 50, 40)
        self.gridLayout_24.setSpacing(30)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.pushButton3 = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton3.sizePolicy().hasHeightForWidth())
        self.pushButton3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton3.setFont(font)
        self.pushButton3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton3.setStyleSheet("color: rgb(220, 70, 70);background-color: rgb(30, 30,30);")
        self.pushButton3.setObjectName("pushButton3")
        self.gridLayout_24.addWidget(self.pushButton3, 3, 0, 1, 1)
        self.formLayout_14 = QtWidgets.QFormLayout()
        self.formLayout_14.setContentsMargins(2, 2, 2, 2)
        self.formLayout_14.setHorizontalSpacing(5)
        self.formLayout_14.setVerticalSpacing(22)
        self.formLayout_14.setObjectName("formLayout_14")
        self.label_16 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(240, 240,240);")
        self.label_16.setObjectName("label_16")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_14.sizePolicy().hasHeightForWidth())
        self.lineEdit_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(220, 220,220);color: rgb(0, 0,0);")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_14)
        self.label_17 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(240, 240,240);")
        self.label_17.setObjectName("label_17")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_15.sizePolicy().hasHeightForWidth())
        self.lineEdit_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(220, 220,220);color: rgb(0, 0,0);")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_15)
        self.checkBox = QtWidgets.QCheckBox(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.checkBox.setFont(font)
        self.checkBox.setIconSize(QtCore.QSize(20, 20))
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.formLayout_14.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("border:none;border-color: #11505C;background-color: rgb(220, 220,220);color: rgb(0, 0,0);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.formLayout_14.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.gridLayout_24.addLayout(self.formLayout_14, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:rgb(150, 150, 150);")
        self.label_20.setObjectName("label_20")
        self.gridLayout_24.addWidget(self.label_20, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.frame_11, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_23, 0, 3, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "服务器IP地址： "))
        self.label_3.setText(_translate("MainWindow", "数据库名称："))
        self.label_4.setText(_translate("MainWindow", "用户名："))
        self.label_5.setText(_translate("MainWindow", "密码："))
        self.label.setText(_translate("MainWindow", "远程数据库设置"))
        self.pushButton1.setText(_translate("MainWindow", "未连接"))
        self.label_14.setText(_translate("MainWindow", "COM端口:     "))
        self.label_15.setText(_translate("MainWindow", "波特率："))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "115200"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "4800"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "9600"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "19200"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "38400"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "43000"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "56000"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "57600"))
        self.pushButton.setText(_translate("MainWindow", "选择文件"))
        self.label_18.setText(_translate("MainWindow", "本地文件转码："))
        self.label_19.setText(_translate("MainWindow", "数传端口设置"))
        self.pushButton2.setText(_translate("MainWindow", "未连接"))
        self.pushButton3.setText(_translate("MainWindow", "未连接"))
        self.label_16.setText(_translate("MainWindow", "视频源路径：    "))
        self.label_17.setText(_translate("MainWindow", "图片保存路径："))
        self.checkBox.setText(_translate("MainWindow", "吊舱控制    "))
        self.label_20.setText(_translate("MainWindow", "图传视频设置"))

